//library imports
const express= require('express');
const {ObjectID}=require("mongodb");  // if the id is autogenerated we have to use the ObjectID as it is not a string it is an objectid
var bodyParser= require('body-parser');


var{User}= require("./../models/users.js"); // users model
var{mongoose}= require("./../db/mongoose.js");  
var{playlist}= require("./../models/playlists.js"); // playlists model

///////////
var app=express();
//configures the middlewear
app.use(bodyParser.json());

//PLaylist name is to bs passsed in the request as playlist name is unique for each user
app.delete('/playlists',(req,res)=>{
    var token = req.header('x-auth');
    User.findByToken(token).then((user)=>{
        if(!user){
            return Promise.reject();
        }
    var userId2=user._id;     // id of the owner of the playlist 
    if(!req.body.playlistName){
        return res.status(400).send("Pass the playlistname to delete");
    }
    var playlistName=req.body.playlistName;
    playlist.findOneAndRemove({$and:[{userId:userId2},{playlistName:playlistName }]}).then((delPlaylist)=>{
        if(!delPlaylist){
            
            return res.status(404).send('No playlist found to delete');
        }
        
        res.status(200).send("Playlist deleted succsesfully");

    }).catch((e)=>{
        res.status(400).send();
    })
    }).catch((e)=>{
        res.status(401).send('Unauthorized Access');
    })
});

app.listen(3000,()=>{
    console.log("Started on port 3000 lets");
});


